import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${inter.variable}`}>
        <Providers>
          {children}
          <div className='text-secondary'>asdf</div>
        </Providers>
      </body>
    </html>
  )
}
